
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.natureandharmony.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.natureandharmony.item.WineItem;
import net.mcreator.natureandharmony.item.WhiteWineItem;
import net.mcreator.natureandharmony.item.UnderworldItem;
import net.mcreator.natureandharmony.item.TopazShearsItem;
import net.mcreator.natureandharmony.item.TopazItem;
import net.mcreator.natureandharmony.item.TopazFishingRodItem;
import net.mcreator.natureandharmony.item.TopazChunksItem;
import net.mcreator.natureandharmony.item.TomatoSeedsItem;
import net.mcreator.natureandharmony.item.TomatoItem;
import net.mcreator.natureandharmony.item.SulphurItem;
import net.mcreator.natureandharmony.item.StrawberrySeedsItem;
import net.mcreator.natureandharmony.item.StrawberryItem;
import net.mcreator.natureandharmony.item.SilverThreadItem;
import net.mcreator.natureandharmony.item.SilverIngotItem;
import net.mcreator.natureandharmony.item.RoseGoldSwordItem;
import net.mcreator.natureandharmony.item.RoseGoldShovelItem;
import net.mcreator.natureandharmony.item.RoseGoldPickaxeItem;
import net.mcreator.natureandharmony.item.RoseGoldIngotItem;
import net.mcreator.natureandharmony.item.RoseGoldHoeItem;
import net.mcreator.natureandharmony.item.RoseGoldAxeItem;
import net.mcreator.natureandharmony.item.RoseGoldArmorItem;
import net.mcreator.natureandharmony.item.RawSilverItem;
import net.mcreator.natureandharmony.item.RawRoseGoldItem;
import net.mcreator.natureandharmony.item.RawActiniumItem;
import net.mcreator.natureandharmony.item.QuartzDustItem;
import net.mcreator.natureandharmony.item.MirrorItem;
import net.mcreator.natureandharmony.item.MichriteItem;
import net.mcreator.natureandharmony.item.MicheriteAndQuartzItem;
import net.mcreator.natureandharmony.item.IceSpikeItem;
import net.mcreator.natureandharmony.item.GrapesWhiteItem;
import net.mcreator.natureandharmony.item.GrapesItem;
import net.mcreator.natureandharmony.item.GrapeJuiceItem;
import net.mcreator.natureandharmony.item.GrapeCiderItem;
import net.mcreator.natureandharmony.item.FleshItem;
import net.mcreator.natureandharmony.item.DiamondShardItem;
import net.mcreator.natureandharmony.item.CottonSeedsItem;
import net.mcreator.natureandharmony.item.CottonItem;
import net.mcreator.natureandharmony.item.CookedFleshItem;
import net.mcreator.natureandharmony.item.ChoppedTomatoItem;
import net.mcreator.natureandharmony.item.CactusFruitItem;
import net.mcreator.natureandharmony.item.AppleJuiceItem;
import net.mcreator.natureandharmony.item.AppleCiderItem;
import net.mcreator.natureandharmony.item.ActiniumIngotItem;
import net.mcreator.natureandharmony.item.ActiniumBowItem;
import net.mcreator.natureandharmony.NatureAndHarmonyMod;

public class NatureAndHarmonyModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, NatureAndHarmonyMod.MODID);
	public static final RegistryObject<Item> CRACKED_MOSSY_STONE_BRICKS = block(NatureAndHarmonyModBlocks.CRACKED_MOSSY_STONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_CHISELED_STONE_BRICKS = block(NatureAndHarmonyModBlocks.CRACKED_CHISELED_STONE_BRICKS);
	public static final RegistryObject<Item> MOSSY_CHISELED_STONE_BRICKS = block(NatureAndHarmonyModBlocks.MOSSY_CHISELED_STONE_BRICKS);
	public static final RegistryObject<Item> STONE_TILES = block(NatureAndHarmonyModBlocks.STONE_TILES);
	public static final RegistryObject<Item> CHISELED_STONE_TILES = block(NatureAndHarmonyModBlocks.CHISELED_STONE_TILES);
	public static final RegistryObject<Item> STONE_PILLAR = block(NatureAndHarmonyModBlocks.STONE_PILLAR);
	public static final RegistryObject<Item> STONE_PANEL = block(NatureAndHarmonyModBlocks.STONE_PANEL);
	public static final RegistryObject<Item> STONE_PATH = block(NatureAndHarmonyModBlocks.STONE_PATH);
	public static final RegistryObject<Item> STONE_PATH_DIRT = block(NatureAndHarmonyModBlocks.STONE_PATH_DIRT);
	public static final RegistryObject<Item> STONE_PATH_GRASS = block(NatureAndHarmonyModBlocks.STONE_PATH_GRASS);
	public static final RegistryObject<Item> ASH = block(NatureAndHarmonyModBlocks.ASH);
	public static final RegistryObject<Item> SULPHUR_ORE = block(NatureAndHarmonyModBlocks.SULPHUR_ORE);
	public static final RegistryObject<Item> MARBLE = block(NatureAndHarmonyModBlocks.MARBLE);
	public static final RegistryObject<Item> POLISHED_MARBLE = block(NatureAndHarmonyModBlocks.POLISHED_MARBLE);
	public static final RegistryObject<Item> POLISHED_MARBLE_SLAB = block(NatureAndHarmonyModBlocks.POLISHED_MARBLE_SLAB);
	public static final RegistryObject<Item> POLISHED_MARBLE_STAIRS = block(NatureAndHarmonyModBlocks.POLISHED_MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_PANEL = block(NatureAndHarmonyModBlocks.MARBLE_PANEL);
	public static final RegistryObject<Item> MARBLE_BRICKS = block(NatureAndHarmonyModBlocks.MARBLE_BRICKS);
	public static final RegistryObject<Item> MARBLE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.MARBLE_BRICKS_SLAB);
	public static final RegistryObject<Item> MARBLE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.MARBLE_BRICKS_STAIRS);
	public static final RegistryObject<Item> MARBLE_TILES = block(NatureAndHarmonyModBlocks.MARBLE_TILES);
	public static final RegistryObject<Item> MARBLE_PILLAR_LOWER = block(NatureAndHarmonyModBlocks.MARBLE_PILLAR_LOWER);
	public static final RegistryObject<Item> MARBLE_PILLAR_MIDDLE = block(NatureAndHarmonyModBlocks.MARBLE_PILLAR_MIDDLE);
	public static final RegistryObject<Item> MARBLE_PILLAR_UPPER = block(NatureAndHarmonyModBlocks.MARBLE_PILLAR_UPPER);
	public static final RegistryObject<Item> BLACK_MARBLE = block(NatureAndHarmonyModBlocks.BLACK_MARBLE);
	public static final RegistryObject<Item> POLISHED_BLACK_MARBLE = block(NatureAndHarmonyModBlocks.POLISHED_BLACK_MARBLE);
	public static final RegistryObject<Item> POLISHED_BLACK_MARBLE_SLAB = block(NatureAndHarmonyModBlocks.POLISHED_BLACK_MARBLE_SLAB);
	public static final RegistryObject<Item> POLISHED_BLACK_MARBLE_STAIRS = block(NatureAndHarmonyModBlocks.POLISHED_BLACK_MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_BLACK_PANEL = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_PANEL);
	public static final RegistryObject<Item> MARBLE_BLACK_BRICKS = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_BRICKS);
	public static final RegistryObject<Item> MARBLE_BLACK_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_BRICKS_SLAB);
	public static final RegistryObject<Item> MARBLE_BLACK_STAIRS = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_STAIRS);
	public static final RegistryObject<Item> MARBLE_BLACK_TILES = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_TILES);
	public static final RegistryObject<Item> MARBLE_BLACK_PILLAR_LOWER = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_PILLAR_LOWER);
	public static final RegistryObject<Item> MARBLE_BLACK_PILLAR_MIDDLE = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_PILLAR_MIDDLE);
	public static final RegistryObject<Item> MARBLE_BLACK_PILLAR_UPPER = block(NatureAndHarmonyModBlocks.MARBLE_BLACK_PILLAR_UPPER);
	public static final RegistryObject<Item> LIMESTONE = block(NatureAndHarmonyModBlocks.LIMESTONE);
	public static final RegistryObject<Item> POLISHED_LIMESTONE = block(NatureAndHarmonyModBlocks.POLISHED_LIMESTONE);
	public static final RegistryObject<Item> POLISHED_LIMESTONE_SLAB = block(NatureAndHarmonyModBlocks.POLISHED_LIMESTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_LIMESTONE_STAIRS_RECIPE = block(NatureAndHarmonyModBlocks.POLISHED_LIMESTONE_STAIRS_RECIPE);
	public static final RegistryObject<Item> LIMESTONE_BRICKS = block(NatureAndHarmonyModBlocks.LIMESTONE_BRICKS);
	public static final RegistryObject<Item> CHISELED_LIMESTONE = block(NatureAndHarmonyModBlocks.CHISELED_LIMESTONE);
	public static final RegistryObject<Item> LIMESTONE_TILES = block(NatureAndHarmonyModBlocks.LIMESTONE_TILES);
	public static final RegistryObject<Item> LIMESTONE_TILES_STAIRS = block(NatureAndHarmonyModBlocks.LIMESTONE_TILES_STAIRS);
	public static final RegistryObject<Item> LIMESTONE_TILES_SLAB = block(NatureAndHarmonyModBlocks.LIMESTONE_TILES_SLAB);
	public static final RegistryObject<Item> LIMESTONE_TILES_WALL = block(NatureAndHarmonyModBlocks.LIMESTONE_TILES_WALL);
	public static final RegistryObject<Item> LIMESTONE_CRACKED_BRICKS = block(NatureAndHarmonyModBlocks.LIMESTONE_CRACKED_BRICKS);
	public static final RegistryObject<Item> ANTIMONITE = block(NatureAndHarmonyModBlocks.ANTIMONITE);
	public static final RegistryObject<Item> POLISHED_ANTIMONITE = block(NatureAndHarmonyModBlocks.POLISHED_ANTIMONITE);
	public static final RegistryObject<Item> POLISHED_ANTIMONITE_SLAB = block(NatureAndHarmonyModBlocks.POLISHED_ANTIMONITE_SLAB);
	public static final RegistryObject<Item> POLISHED_ANTIMONITE_STAIRS = block(NatureAndHarmonyModBlocks.POLISHED_ANTIMONITE_STAIRS);
	public static final RegistryObject<Item> ANTIMONITE_PANEL = block(NatureAndHarmonyModBlocks.ANTIMONITE_PANEL);
	public static final RegistryObject<Item> ANTIMONITE_PANEL_SLAB = block(NatureAndHarmonyModBlocks.ANTIMONITE_PANEL_SLAB);
	public static final RegistryObject<Item> ANTIMONITE_PANEL_STAIRS_RECIPE = block(NatureAndHarmonyModBlocks.ANTIMONITE_PANEL_STAIRS_RECIPE);
	public static final RegistryObject<Item> ANTIMONITE_TILES = block(NatureAndHarmonyModBlocks.ANTIMONITE_TILES);
	public static final RegistryObject<Item> ANTIMONITE_PATTERNED = block(NatureAndHarmonyModBlocks.ANTIMONITE_PATTERNED);
	public static final RegistryObject<Item> ANTIMONITE_CHISELED = block(NatureAndHarmonyModBlocks.ANTIMONITE_CHISELED);
	public static final RegistryObject<Item> ANTHRACITE = block(NatureAndHarmonyModBlocks.ANTHRACITE);
	public static final RegistryObject<Item> POLISHED_ANTHRACITE = block(NatureAndHarmonyModBlocks.POLISHED_ANTHRACITE);
	public static final RegistryObject<Item> POLISHED_ANTHRACITE_SLAB = block(NatureAndHarmonyModBlocks.POLISHED_ANTHRACITE_SLAB);
	public static final RegistryObject<Item> POLISHED_ANTHRACITE_STAIRS = block(NatureAndHarmonyModBlocks.POLISHED_ANTHRACITE_STAIRS);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS_SLAB);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> ANTHRACITE_TILED_BRICKS = block(NatureAndHarmonyModBlocks.ANTHRACITE_TILED_BRICKS);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS_SMALL = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS_SMALL);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS_SMALL_SLAB = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS_SMALL_SLAB);
	public static final RegistryObject<Item> ANTHRACITE_BRICKS_SMALL_STAIRS = block(NatureAndHarmonyModBlocks.ANTHRACITE_BRICKS_SMALL_STAIRS);
	public static final RegistryObject<Item> ANTHRACITE_SMALL_TILES = block(NatureAndHarmonyModBlocks.ANTHRACITE_SMALL_TILES);
	public static final RegistryObject<Item> ASH_GILDED_GOLD = block(NatureAndHarmonyModBlocks.ASH_GILDED_GOLD);
	public static final RegistryObject<Item> ASH_GILDED_IRON = block(NatureAndHarmonyModBlocks.ASH_GILDED_IRON);
	public static final RegistryObject<Item> ASH_GILDED_DIAMOND = block(NatureAndHarmonyModBlocks.ASH_GILDED_DIAMOND);
	public static final RegistryObject<Item> WITHERED_MOSS = block(NatureAndHarmonyModBlocks.WITHERED_MOSS);
	public static final RegistryObject<Item> LARGE_CHAINS = block(NatureAndHarmonyModBlocks.LARGE_CHAINS);
	public static final RegistryObject<Item> LARGE_LANTERN = block(NatureAndHarmonyModBlocks.LARGE_LANTERN);
	public static final RegistryObject<Item> LARGE_LANTERN_WALL = block(NatureAndHarmonyModBlocks.LARGE_LANTERN_WALL);
	public static final RegistryObject<Item> SULPHUR = REGISTRY.register("sulphur", () -> new SulphurItem());
	public static final RegistryObject<Item> DIAMOND_SHARD = REGISTRY.register("diamond_shard", () -> new DiamondShardItem());
	public static final RegistryObject<Item> RED_ROSE = block(NatureAndHarmonyModBlocks.RED_ROSE);
	public static final RegistryObject<Item> PINK_ROSE = block(NatureAndHarmonyModBlocks.PINK_ROSE);
	public static final RegistryObject<Item> CYAN_ROSE = block(NatureAndHarmonyModBlocks.CYAN_ROSE);
	public static final RegistryObject<Item> WHITE_ROSE = block(NatureAndHarmonyModBlocks.WHITE_ROSE);
	public static final RegistryObject<Item> ASH_TUFFS = block(NatureAndHarmonyModBlocks.ASH_TUFFS);
	public static final RegistryObject<Item> GRAPES = REGISTRY.register("grapes", () -> new GrapesItem());
	public static final RegistryObject<Item> GRAPES_WHITE = REGISTRY.register("grapes_white", () -> new GrapesWhiteItem());
	public static final RegistryObject<Item> GRAPE_JUICE = REGISTRY.register("grape_juice", () -> new GrapeJuiceItem());
	public static final RegistryObject<Item> WINE = REGISTRY.register("wine", () -> new WineItem());
	public static final RegistryObject<Item> APPLE_CIDER = REGISTRY.register("apple_cider", () -> new AppleCiderItem());
	public static final RegistryObject<Item> GRAPE_CIDER = REGISTRY.register("grape_cider", () -> new GrapeCiderItem());
	public static final RegistryObject<Item> APPLE_JUICE = REGISTRY.register("apple_juice", () -> new AppleJuiceItem());
	public static final RegistryObject<Item> WHITE_WINE = REGISTRY.register("white_wine", () -> new WhiteWineItem());
	public static final RegistryObject<Item> GRAPE_STAGE_1 = block(NatureAndHarmonyModBlocks.GRAPE_STAGE_1);
	public static final RegistryObject<Item> GRAPE_STAGE_2 = block(NatureAndHarmonyModBlocks.GRAPE_STAGE_2);
	public static final RegistryObject<Item> GRAPE_STAGE_3 = block(NatureAndHarmonyModBlocks.GRAPE_STAGE_3);
	public static final RegistryObject<Item> GRAPE_STAGE_4 = block(NatureAndHarmonyModBlocks.GRAPE_STAGE_4);
	public static final RegistryObject<Item> GRAPE_STAGE_5 = block(NatureAndHarmonyModBlocks.GRAPE_STAGE_5);
	public static final RegistryObject<Item> GRAPES_WHITE_STAGE_1 = block(NatureAndHarmonyModBlocks.GRAPES_WHITE_STAGE_1);
	public static final RegistryObject<Item> GRAPES_WHITE_STAGE_2 = block(NatureAndHarmonyModBlocks.GRAPES_WHITE_STAGE_2);
	public static final RegistryObject<Item> GRAPES_WHITE_STAGE_3 = block(NatureAndHarmonyModBlocks.GRAPES_WHITE_STAGE_3);
	public static final RegistryObject<Item> GRAPES_WHITE_STAGE_4 = block(NatureAndHarmonyModBlocks.GRAPES_WHITE_STAGE_4);
	public static final RegistryObject<Item> GRAPES_WHITE_STAGE_5 = block(NatureAndHarmonyModBlocks.GRAPES_WHITE_STAGE_5);
	public static final RegistryObject<Item> MIRROR = REGISTRY.register("mirror", () -> new MirrorItem());
	public static final RegistryObject<Item> EMINENCE_STEM = block(NatureAndHarmonyModBlocks.EMINENCE_STEM);
	public static final RegistryObject<Item> EMINENCE_PLANKS_STAIRS = block(NatureAndHarmonyModBlocks.EMINENCE_PLANKS_STAIRS);
	public static final RegistryObject<Item> EMINENCE_PLANKS_SLAB = block(NatureAndHarmonyModBlocks.EMINENCE_PLANKS_SLAB);
	public static final RegistryObject<Item> EMINENCE_FENCE = block(NatureAndHarmonyModBlocks.EMINENCE_FENCE);
	public static final RegistryObject<Item> EMINENCE_FENCE_GATE = block(NatureAndHarmonyModBlocks.EMINENCE_FENCE_GATE);
	public static final RegistryObject<Item> EMINENCE_DOOR = doubleBlock(NatureAndHarmonyModBlocks.EMINENCE_DOOR);
	public static final RegistryObject<Item> EMINENCE_TRAPDOOR = block(NatureAndHarmonyModBlocks.EMINENCE_TRAPDOOR);
	public static final RegistryObject<Item> EMINENCE_ROOTS = block(NatureAndHarmonyModBlocks.EMINENCE_ROOTS);
	public static final RegistryObject<Item> EMINENCE_FLOWER = doubleBlock(NatureAndHarmonyModBlocks.EMINENCE_FLOWER);
	public static final RegistryObject<Item> EMINENCE_FUNGUS = block(NatureAndHarmonyModBlocks.EMINENCE_FUNGUS);
	public static final RegistryObject<Item> EMINENCE_WART = block(NatureAndHarmonyModBlocks.EMINENCE_WART);
	public static final RegistryObject<Item> CAST_IRON_BLOCK = block(NatureAndHarmonyModBlocks.CAST_IRON_BLOCK);
	public static final RegistryObject<Item> CUT_CAST_IRON = block(NatureAndHarmonyModBlocks.CUT_CAST_IRON);
	public static final RegistryObject<Item> CUT_IRON_PANELS = block(NatureAndHarmonyModBlocks.CUT_IRON_PANELS);
	public static final RegistryObject<Item> MOSSY_NETHERRACK = block(NatureAndHarmonyModBlocks.MOSSY_NETHERRACK);
	public static final RegistryObject<Item> CARVED_STONE_PANEL = block(NatureAndHarmonyModBlocks.CARVED_STONE_PANEL);
	public static final RegistryObject<Item> LEATHER_BLOCK = block(NatureAndHarmonyModBlocks.LEATHER_BLOCK);
	public static final RegistryObject<Item> SKULL_SPAWN_EGG = REGISTRY.register("skull_spawn_egg", () -> new ForgeSpawnEggItem(NatureAndHarmonyModEntities.SKULL, -393267, -4409, new Item.Properties()));
	public static final RegistryObject<Item> CALCITE_BRICKS = block(NatureAndHarmonyModBlocks.CALCITE_BRICKS);
	public static final RegistryObject<Item> CALCITE_POLISHED = block(NatureAndHarmonyModBlocks.CALCITE_POLISHED);
	public static final RegistryObject<Item> CALCITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.CALCITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> CALCITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.CALCITE_BRICKS_SLAB);
	public static final RegistryObject<Item> CALCITE_BRICKS_WALL = block(NatureAndHarmonyModBlocks.CALCITE_BRICKS_WALL);
	public static final RegistryObject<Item> CALCITE_PATH = block(NatureAndHarmonyModBlocks.CALCITE_PATH);
	public static final RegistryObject<Item> CALCITE_PATH_DIRT = block(NatureAndHarmonyModBlocks.CALCITE_PATH_DIRT);
	public static final RegistryObject<Item> CALCITE_PATH_GRASS = block(NatureAndHarmonyModBlocks.CALCITE_PATH_GRASS);
	public static final RegistryObject<Item> TUFF_BRICKS = block(NatureAndHarmonyModBlocks.TUFF_BRICKS);
	public static final RegistryObject<Item> TUFF_TILES = block(NatureAndHarmonyModBlocks.TUFF_TILES);
	public static final RegistryObject<Item> TUFF_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.TUFF_BRICKS_STAIRS);
	public static final RegistryObject<Item> TUFF_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.TUFF_BRICKS_SLAB);
	public static final RegistryObject<Item> TUFF_BRICKS_WALL = block(NatureAndHarmonyModBlocks.TUFF_BRICKS_WALL);
	public static final RegistryObject<Item> TUFF_PATH = block(NatureAndHarmonyModBlocks.TUFF_PATH);
	public static final RegistryObject<Item> TUFF_PATH_DIRT = block(NatureAndHarmonyModBlocks.TUFF_PATH_DIRT);
	public static final RegistryObject<Item> TUFF_PATH_GRASS = block(NatureAndHarmonyModBlocks.TUFF_PATH_GRASS);
	public static final RegistryObject<Item> SCORIA_GRAY = block(NatureAndHarmonyModBlocks.SCORIA_GRAY);
	public static final RegistryObject<Item> SCORIA_POLISHED = block(NatureAndHarmonyModBlocks.SCORIA_POLISHED);
	public static final RegistryObject<Item> SCORIA_BRICKS = block(NatureAndHarmonyModBlocks.SCORIA_BRICKS);
	public static final RegistryObject<Item> SCORIA_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.SCORIA_BRICKS_STAIRS);
	public static final RegistryObject<Item> SCORIA_BRICKS_SLAB_RECIPE = block(NatureAndHarmonyModBlocks.SCORIA_BRICKS_SLAB_RECIPE);
	public static final RegistryObject<Item> SCORIA_RED = block(NatureAndHarmonyModBlocks.SCORIA_RED);
	public static final RegistryObject<Item> SCORIA_RED_POLISHED = block(NatureAndHarmonyModBlocks.SCORIA_RED_POLISHED);
	public static final RegistryObject<Item> SCORIA_RED_BRICKS = block(NatureAndHarmonyModBlocks.SCORIA_RED_BRICKS);
	public static final RegistryObject<Item> SCORIA_RED_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.SCORIA_RED_BRICKS_STAIRS);
	public static final RegistryObject<Item> SCORIA_RED_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.SCORIA_RED_BRICKS_SLAB);
	public static final RegistryObject<Item> NETHERRACK_PATH = block(NatureAndHarmonyModBlocks.NETHERRACK_PATH);
	public static final RegistryObject<Item> NETHERRACK_PATH_CRIMSON_NYLIUM = block(NatureAndHarmonyModBlocks.NETHERRACK_PATH_CRIMSON_NYLIUM);
	public static final RegistryObject<Item> NETHERRACK_PATH_WARPED_NYLIUM = block(NatureAndHarmonyModBlocks.NETHERRACK_PATH_WARPED_NYLIUM);
	public static final RegistryObject<Item> CUT_DIRT = block(NatureAndHarmonyModBlocks.CUT_DIRT);
	public static final RegistryObject<Item> CAST_IRON_TILES = block(NatureAndHarmonyModBlocks.CAST_IRON_TILES);
	public static final RegistryObject<Item> LARGE_CAST_IRON_BLOCK = block(NatureAndHarmonyModBlocks.LARGE_CAST_IRON_BLOCK);
	public static final RegistryObject<Item> SMOOTH_CUT_CAST_IRON = block(NatureAndHarmonyModBlocks.SMOOTH_CUT_CAST_IRON);
	public static final RegistryObject<Item> SMOOTH_CAST_IRON_BLOCK = block(NatureAndHarmonyModBlocks.SMOOTH_CAST_IRON_BLOCK);
	public static final RegistryObject<Item> RIBBED_CAST_IRON = block(NatureAndHarmonyModBlocks.RIBBED_CAST_IRON);
	public static final RegistryObject<Item> FLESH = REGISTRY.register("flesh", () -> new FleshItem());
	public static final RegistryObject<Item> COOKED_FLESH = REGISTRY.register("cooked_flesh", () -> new CookedFleshItem());
	public static final RegistryObject<Item> TOPAZ_CHUNKS = REGISTRY.register("topaz_chunks", () -> new TopazChunksItem());
	public static final RegistryObject<Item> TOPAZ = REGISTRY.register("topaz", () -> new TopazItem());
	public static final RegistryObject<Item> TOPAZ_ORE = block(NatureAndHarmonyModBlocks.TOPAZ_ORE);
	public static final RegistryObject<Item> TOPAZ_SHEARS = REGISTRY.register("topaz_shears", () -> new TopazShearsItem());
	public static final RegistryObject<Item> TOPAZ_FISHING_ROD = REGISTRY.register("topaz_fishing_rod", () -> new TopazFishingRodItem());
	public static final RegistryObject<Item> TOPAZ_BLOCK = block(NatureAndHarmonyModBlocks.TOPAZ_BLOCK);
	public static final RegistryObject<Item> POLISHED_STONE = block(NatureAndHarmonyModBlocks.POLISHED_STONE);
	public static final RegistryObject<Item> GLOWING_OBSIDIAN = block(NatureAndHarmonyModBlocks.GLOWING_OBSIDIAN);
	public static final RegistryObject<Item> UNDERWORLD = REGISTRY.register("underworld", () -> new UnderworldItem());
	public static final RegistryObject<Item> UNDERWORLD_DIRT = block(NatureAndHarmonyModBlocks.UNDERWORLD_DIRT);
	public static final RegistryObject<Item> UNDERWORLD_GRASS = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS);
	public static final RegistryObject<Item> CARBORITE = block(NatureAndHarmonyModBlocks.CARBORITE);
	public static final RegistryObject<Item> CARBORITE_POLISHED = block(NatureAndHarmonyModBlocks.CARBORITE_POLISHED);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_PLANT = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_PLANT);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_TUFTS = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_TUFTS);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_FLOWEREDF = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_FLOWEREDF);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_TALL = doubleBlock(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_TALL);
	public static final RegistryObject<Item> BLOOD_OAK_LOG = block(NatureAndHarmonyModBlocks.BLOOD_OAK_LOG);
	public static final RegistryObject<Item> BLOOD_OAK_LEAVES = block(NatureAndHarmonyModBlocks.BLOOD_OAK_LEAVES);
	public static final RegistryObject<Item> BLOOD_OAK_PLANKS = block(NatureAndHarmonyModBlocks.BLOOD_OAK_PLANKS);
	public static final RegistryObject<Item> BLOOD_OAK_PLANKS_STAIRS = block(NatureAndHarmonyModBlocks.BLOOD_OAK_PLANKS_STAIRS);
	public static final RegistryObject<Item> BLOOD_OAK_SLAB = block(NatureAndHarmonyModBlocks.BLOOD_OAK_SLAB);
	public static final RegistryObject<Item> BLOOD_OAK_FENCE = block(NatureAndHarmonyModBlocks.BLOOD_OAK_FENCE);
	public static final RegistryObject<Item> BLOOD_OAK_FENCE_GATE = block(NatureAndHarmonyModBlocks.BLOOD_OAK_FENCE_GATE);
	public static final RegistryObject<Item> BLOOD_OAK_PRESSURE_PLATE = block(NatureAndHarmonyModBlocks.BLOOD_OAK_PRESSURE_PLATE);
	public static final RegistryObject<Item> BLOOD_OAK_BUTTON = block(NatureAndHarmonyModBlocks.BLOOD_OAK_BUTTON);
	public static final RegistryObject<Item> BLOOD_OAK_DOOR = doubleBlock(NatureAndHarmonyModBlocks.BLOOD_OAK_DOOR);
	public static final RegistryObject<Item> BLOOD_OAK_TRAPDOOR = block(NatureAndHarmonyModBlocks.BLOOD_OAK_TRAPDOOR);
	public static final RegistryObject<Item> FROST = block(NatureAndHarmonyModBlocks.FROST);
	public static final RegistryObject<Item> PEAK_SCHIST = block(NatureAndHarmonyModBlocks.PEAK_SCHIST);
	public static final RegistryObject<Item> PEAK_SCHIST_POLISHED = block(NatureAndHarmonyModBlocks.PEAK_SCHIST_POLISHED);
	public static final RegistryObject<Item> PEAK_SCHIST_STAIRS = block(NatureAndHarmonyModBlocks.PEAK_SCHIST_STAIRS);
	public static final RegistryObject<Item> PEAK_SCHIST_SLAB = block(NatureAndHarmonyModBlocks.PEAK_SCHIST_SLAB);
	public static final RegistryObject<Item> PEAK_SCHIST_BRICKS = block(NatureAndHarmonyModBlocks.PEAK_SCHIST_BRICKS);
	public static final RegistryObject<Item> PEAK_SCHIST_BRICKS_WALL = block(NatureAndHarmonyModBlocks.PEAK_SCHIST_BRICKS_WALL);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_FROSTED = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_FROSTED);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_SHORT_FROSTED = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_SHORT_FROSTED);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_TALL_FROSTED = doubleBlock(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_TALL_FROSTED);
	public static final RegistryObject<Item> UNDERWORLD_BELLFLOWER = doubleBlock(NatureAndHarmonyModBlocks.UNDERWORLD_BELLFLOWER);
	public static final RegistryObject<Item> PURPLE_BURST_FLOWER = doubleBlock(NatureAndHarmonyModBlocks.PURPLE_BURST_FLOWER);
	public static final RegistryObject<Item> YELLOW_BURSTDFLOWER = doubleBlock(NatureAndHarmonyModBlocks.YELLOW_BURSTDFLOWER);
	public static final RegistryObject<Item> BUDDED_FLOWER = doubleBlock(NatureAndHarmonyModBlocks.BUDDED_FLOWER);
	public static final RegistryObject<Item> CIRCULATUM_FLOWER = block(NatureAndHarmonyModBlocks.CIRCULATUM_FLOWER);
	public static final RegistryObject<Item> OPEN_FLOWER = block(NatureAndHarmonyModBlocks.OPEN_FLOWER);
	public static final RegistryObject<Item> SUN_DIAL_FLOWER = block(NatureAndHarmonyModBlocks.SUN_DIAL_FLOWER);
	public static final RegistryObject<Item> CARBORITE_COBBLESTONE = block(NatureAndHarmonyModBlocks.CARBORITE_COBBLESTONE);
	public static final RegistryObject<Item> CRACKED_CARBORITE = block(NatureAndHarmonyModBlocks.CRACKED_CARBORITE);
	public static final RegistryObject<Item> VEKRENITE = block(NatureAndHarmonyModBlocks.VEKRENITE);
	public static final RegistryObject<Item> VEKRENITE_POLISHED = block(NatureAndHarmonyModBlocks.VEKRENITE_POLISHED);
	public static final RegistryObject<Item> VEKRENITE_BRICKS = block(NatureAndHarmonyModBlocks.VEKRENITE_BRICKS);
	public static final RegistryObject<Item> VEKRENITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.VEKRENITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> VEKRENITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.VEKRENITE_BRICKS_SLAB);
	public static final RegistryObject<Item> VEKRENITE_BRICKS_WALL = block(NatureAndHarmonyModBlocks.VEKRENITE_BRICKS_WALL);
	public static final RegistryObject<Item> ROSE_GOLD_ORE = block(NatureAndHarmonyModBlocks.ROSE_GOLD_ORE);
	public static final RegistryObject<Item> ROSE_GOLD_BLOCK = block(NatureAndHarmonyModBlocks.ROSE_GOLD_BLOCK);
	public static final RegistryObject<Item> ROSE_GOLD_INGOT = REGISTRY.register("rose_gold_ingot", () -> new RoseGoldIngotItem());
	public static final RegistryObject<Item> ROSE_GOLD_PICKAXE = REGISTRY.register("rose_gold_pickaxe", () -> new RoseGoldPickaxeItem());
	public static final RegistryObject<Item> ROSE_GOLD_AXE = REGISTRY.register("rose_gold_axe", () -> new RoseGoldAxeItem());
	public static final RegistryObject<Item> ROSE_GOLD_SWORD = REGISTRY.register("rose_gold_sword", () -> new RoseGoldSwordItem());
	public static final RegistryObject<Item> ROSE_GOLD_SHOVEL = REGISTRY.register("rose_gold_shovel", () -> new RoseGoldShovelItem());
	public static final RegistryObject<Item> ROSE_GOLD_HOE = REGISTRY.register("rose_gold_hoe", () -> new RoseGoldHoeItem());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_HELMET = REGISTRY.register("rose_gold_armor_helmet", () -> new RoseGoldArmorItem.Helmet());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_CHESTPLATE = REGISTRY.register("rose_gold_armor_chestplate", () -> new RoseGoldArmorItem.Chestplate());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_LEGGINGS = REGISTRY.register("rose_gold_armor_leggings", () -> new RoseGoldArmorItem.Leggings());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_BOOTS = REGISTRY.register("rose_gold_armor_boots", () -> new RoseGoldArmorItem.Boots());
	public static final RegistryObject<Item> RAW_ROSE_GOLD = REGISTRY.register("raw_rose_gold", () -> new RawRoseGoldItem());
	public static final RegistryObject<Item> RAW_ROSE_GOLD_BLOCK = block(NatureAndHarmonyModBlocks.RAW_ROSE_GOLD_BLOCK);
	public static final RegistryObject<Item> COTTON_STAGE_1 = block(NatureAndHarmonyModBlocks.COTTON_STAGE_1);
	public static final RegistryObject<Item> COTTON_STAGE_2 = block(NatureAndHarmonyModBlocks.COTTON_STAGE_2);
	public static final RegistryObject<Item> COTTON_STAGE_3 = block(NatureAndHarmonyModBlocks.COTTON_STAGE_3);
	public static final RegistryObject<Item> COTTON_STAGE_4 = block(NatureAndHarmonyModBlocks.COTTON_STAGE_4);
	public static final RegistryObject<Item> COTTON = REGISTRY.register("cotton", () -> new CottonItem());
	public static final RegistryObject<Item> COTTON_SEEDS = REGISTRY.register("cotton_seeds", () -> new CottonSeedsItem());
	public static final RegistryObject<Item> STRAWBERRY_STAGE_1 = block(NatureAndHarmonyModBlocks.STRAWBERRY_STAGE_1);
	public static final RegistryObject<Item> STRAWBERRY_STAGE_2 = block(NatureAndHarmonyModBlocks.STRAWBERRY_STAGE_2);
	public static final RegistryObject<Item> STRAWBERRY_STAGE_3 = block(NatureAndHarmonyModBlocks.STRAWBERRY_STAGE_3);
	public static final RegistryObject<Item> STRAWBERRY_STAGE_4 = block(NatureAndHarmonyModBlocks.STRAWBERRY_STAGE_4);
	public static final RegistryObject<Item> STRAWBERRY_STAGE_5 = block(NatureAndHarmonyModBlocks.STRAWBERRY_STAGE_5);
	public static final RegistryObject<Item> STRAWBERRY_SEEDS = REGISTRY.register("strawberry_seeds", () -> new StrawberrySeedsItem());
	public static final RegistryObject<Item> STRAWBERRY = REGISTRY.register("strawberry", () -> new StrawberryItem());
	public static final RegistryObject<Item> TOMATO_STAGE_1 = block(NatureAndHarmonyModBlocks.TOMATO_STAGE_1);
	public static final RegistryObject<Item> TOMATO_STAGE_2 = block(NatureAndHarmonyModBlocks.TOMATO_STAGE_2);
	public static final RegistryObject<Item> TOMATO_STAGE_3 = block(NatureAndHarmonyModBlocks.TOMATO_STAGE_3);
	public static final RegistryObject<Item> TOMATO_STAGE_4 = block(NatureAndHarmonyModBlocks.TOMATO_STAGE_4);
	public static final RegistryObject<Item> TOMATO_STAGE_5 = block(NatureAndHarmonyModBlocks.TOMATO_STAGE_5);
	public static final RegistryObject<Item> TOMATO_SEEDS = REGISTRY.register("tomato_seeds", () -> new TomatoSeedsItem());
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new TomatoItem());
	public static final RegistryObject<Item> CHOPPED_TOMATO = REGISTRY.register("chopped_tomato", () -> new ChoppedTomatoItem());
	public static final RegistryObject<Item> BAUXITE = block(NatureAndHarmonyModBlocks.BAUXITE);
	public static final RegistryObject<Item> BAUXITE_POLISHED = block(NatureAndHarmonyModBlocks.BAUXITE_POLISHED);
	public static final RegistryObject<Item> BAUXITE_POLISHED_STAIRS = block(NatureAndHarmonyModBlocks.BAUXITE_POLISHED_STAIRS);
	public static final RegistryObject<Item> BAUXITE_POLISHED_SLAB = block(NatureAndHarmonyModBlocks.BAUXITE_POLISHED_SLAB);
	public static final RegistryObject<Item> CORKITE = block(NatureAndHarmonyModBlocks.CORKITE);
	public static final RegistryObject<Item> POLISHED_CORKITE = block(NatureAndHarmonyModBlocks.POLISHED_CORKITE);
	public static final RegistryObject<Item> CORKITE_POLISHED_STAIRS = block(NatureAndHarmonyModBlocks.CORKITE_POLISHED_STAIRS);
	public static final RegistryObject<Item> CORKITE_BRICKS = block(NatureAndHarmonyModBlocks.CORKITE_BRICKS);
	public static final RegistryObject<Item> CORKITE_POLISHED_SLAB = block(NatureAndHarmonyModBlocks.CORKITE_POLISHED_SLAB);
	public static final RegistryObject<Item> HEATED_CORKITE = block(NatureAndHarmonyModBlocks.HEATED_CORKITE);
	public static final RegistryObject<Item> MORGONITE = block(NatureAndHarmonyModBlocks.MORGONITE);
	public static final RegistryObject<Item> MORGONITE_POLISHED = block(NatureAndHarmonyModBlocks.MORGONITE_POLISHED);
	public static final RegistryObject<Item> MORGONITE_BRICKS = block(NatureAndHarmonyModBlocks.MORGONITE_BRICKS);
	public static final RegistryObject<Item> MORGONITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.MORGONITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> MORGONITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.MORGONITE_BRICKS_SLAB);
	public static final RegistryObject<Item> VENOMITE = block(NatureAndHarmonyModBlocks.VENOMITE);
	public static final RegistryObject<Item> VENOMITE_POLISHED = block(NatureAndHarmonyModBlocks.VENOMITE_POLISHED);
	public static final RegistryObject<Item> VENOMITE_POLISHED_STAIRS = block(NatureAndHarmonyModBlocks.VENOMITE_POLISHED_STAIRS);
	public static final RegistryObject<Item> VENOMITE_POLISHED_SLAB = block(NatureAndHarmonyModBlocks.VENOMITE_POLISHED_SLAB);
	public static final RegistryObject<Item> RHODUSITE = block(NatureAndHarmonyModBlocks.RHODUSITE);
	public static final RegistryObject<Item> RHODUSITE_POLISHED = block(NatureAndHarmonyModBlocks.RHODUSITE_POLISHED);
	public static final RegistryObject<Item> RHODUSITE_BRICKS = block(NatureAndHarmonyModBlocks.RHODUSITE_BRICKS);
	public static final RegistryObject<Item> RHODUSITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.RHODUSITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> RHODUSITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.RHODUSITE_BRICKS_SLAB);
	public static final RegistryObject<Item> MICHRITE = REGISTRY.register("michrite", () -> new MichriteItem());
	public static final RegistryObject<Item> GREEN_FIRE = block(NatureAndHarmonyModBlocks.GREEN_FIRE);
	public static final RegistryObject<Item> MICHERITE_AND_QUARTZ = REGISTRY.register("micherite_and_quartz", () -> new MicheriteAndQuartzItem());
	public static final RegistryObject<Item> MICHERITE_ORE = block(NatureAndHarmonyModBlocks.MICHERITE_ORE);
	public static final RegistryObject<Item> QUARTZ_DUST = REGISTRY.register("quartz_dust", () -> new QuartzDustItem());
	public static final RegistryObject<Item> QUARTZ_DUST_BLOCK = block(NatureAndHarmonyModBlocks.QUARTZ_DUST_BLOCK);
	public static final RegistryObject<Item> ICE_SPIKE = REGISTRY.register("ice_spike", () -> new IceSpikeItem());
	public static final RegistryObject<Item> ICE_SPIKE_BLOCK = block(NatureAndHarmonyModBlocks.ICE_SPIKE_BLOCK);
	public static final RegistryObject<Item> TALL_ICE_SPIKE_BLOCK = doubleBlock(NatureAndHarmonyModBlocks.TALL_ICE_SPIKE_BLOCK);
	public static final RegistryObject<Item> CHALK_WHITE = block(NatureAndHarmonyModBlocks.CHALK_WHITE);
	public static final RegistryObject<Item> CHALK_BLUE = block(NatureAndHarmonyModBlocks.CHALK_BLUE);
	public static final RegistryObject<Item> CHALK_RED = block(NatureAndHarmonyModBlocks.CHALK_RED);
	public static final RegistryObject<Item> CREAMALAN = block(NatureAndHarmonyModBlocks.CREAMALAN);
	public static final RegistryObject<Item> CREAMALEN_POLISHED = block(NatureAndHarmonyModBlocks.CREAMALEN_POLISHED);
	public static final RegistryObject<Item> CREAMALEN_COBBLESTONE = block(NatureAndHarmonyModBlocks.CREAMALEN_COBBLESTONE);
	public static final RegistryObject<Item> CREAMALEN_SMOOTH = block(NatureAndHarmonyModBlocks.CREAMALEN_SMOOTH);
	public static final RegistryObject<Item> DARKONITE = block(NatureAndHarmonyModBlocks.DARKONITE);
	public static final RegistryObject<Item> DARKONITE_SNOWY = block(NatureAndHarmonyModBlocks.DARKONITE_SNOWY);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_RED = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_RED);
	public static final RegistryObject<Item> UNDERWORLD_GRASS_RED_FLOWERED = block(NatureAndHarmonyModBlocks.UNDERWORLD_GRASS_RED_FLOWERED);
	public static final RegistryObject<Item> DARKONITE_POLISHED = block(NatureAndHarmonyModBlocks.DARKONITE_POLISHED);
	public static final RegistryObject<Item> DARKONITE_POLISHED_STAIRS = block(NatureAndHarmonyModBlocks.DARKONITE_POLISHED_STAIRS);
	public static final RegistryObject<Item> DARKONITE_POLISHED_SLAB = block(NatureAndHarmonyModBlocks.DARKONITE_POLISHED_SLAB);
	public static final RegistryObject<Item> DARKONITE_BRICKS = block(NatureAndHarmonyModBlocks.DARKONITE_BRICKS);
	public static final RegistryObject<Item> DARKONITE_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.DARKONITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> DARKONITE_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.DARKONITE_BRICKS_SLAB);
	public static final RegistryObject<Item> DARKONITE_CHISELED = block(NatureAndHarmonyModBlocks.DARKONITE_CHISELED);
	public static final RegistryObject<Item> DARKONITE_TILES = block(NatureAndHarmonyModBlocks.DARKONITE_TILES);
	public static final RegistryObject<Item> DARKONITE_CARVED = block(NatureAndHarmonyModBlocks.DARKONITE_CARVED);
	public static final RegistryObject<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", () -> new SilverIngotItem());
	public static final RegistryObject<Item> RAW_SILVER = REGISTRY.register("raw_silver", () -> new RawSilverItem());
	public static final RegistryObject<Item> RAW_SILVER_BLOCK = block(NatureAndHarmonyModBlocks.RAW_SILVER_BLOCK);
	public static final RegistryObject<Item> SILVER_ORE = block(NatureAndHarmonyModBlocks.SILVER_ORE);
	public static final RegistryObject<Item> SILVER_THREAD = REGISTRY.register("silver_thread", () -> new SilverThreadItem());
	public static final RegistryObject<Item> RAW_ACTINIUM_BLOCK = block(NatureAndHarmonyModBlocks.RAW_ACTINIUM_BLOCK);
	public static final RegistryObject<Item> ACTINIUM_ORE = block(NatureAndHarmonyModBlocks.ACTINIUM_ORE);
	public static final RegistryObject<Item> ACTINIUM_INGOT = REGISTRY.register("actinium_ingot", () -> new ActiniumIngotItem());
	public static final RegistryObject<Item> RAW_ACTINIUM = REGISTRY.register("raw_actinium", () -> new RawActiniumItem());
	public static final RegistryObject<Item> ACTINIUM_BOW = REGISTRY.register("actinium_bow", () -> new ActiniumBowItem());
	public static final RegistryObject<Item> UNDERWORLD_SAND = block(NatureAndHarmonyModBlocks.UNDERWORLD_SAND);
	public static final RegistryObject<Item> UNDERWORLD_SANDSTONE = block(NatureAndHarmonyModBlocks.UNDERWORLD_SANDSTONE);
	public static final RegistryObject<Item> CACTUS_FRUIT = REGISTRY.register("cactus_fruit", () -> new CactusFruitItem());
	public static final RegistryObject<Item> CACTUS = block(NatureAndHarmonyModBlocks.CACTUS);
	public static final RegistryObject<Item> DEAD_WEEDS = block(NatureAndHarmonyModBlocks.DEAD_WEEDS);
	public static final RegistryObject<Item> DEAD_WEEDS_2 = block(NatureAndHarmonyModBlocks.DEAD_WEEDS_2);
	public static final RegistryObject<Item> DEAD_WEEDS_3 = block(NatureAndHarmonyModBlocks.DEAD_WEEDS_3);
	public static final RegistryObject<Item> DARKONITE_BLACK = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK);
	public static final RegistryObject<Item> DARKONITE_BLACK_POLISHED = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_POLISHED);
	public static final RegistryObject<Item> DARKONITE_BLACK_POLISHED_STAIRS = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_POLISHED_STAIRS);
	public static final RegistryObject<Item> DARKONITE_BLACK_POLISHED_SLAB = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_POLISHED_SLAB);
	public static final RegistryObject<Item> DARKONITE_BLACK_BRICKS = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_BRICKS);
	public static final RegistryObject<Item> DARKONITE_BLACK_BRICKS_STAIRS = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_BRICKS_STAIRS);
	public static final RegistryObject<Item> DARKONITE_BLACK_BRICKS_SLAB = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_BRICKS_SLAB);
	public static final RegistryObject<Item> DARKONITE_BLACK_CHISELED = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_CHISELED);
	public static final RegistryObject<Item> DARKONITE_BLACK_TILES = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_TILES);
	public static final RegistryObject<Item> DARKONITE_BLACK_CARVED = block(NatureAndHarmonyModBlocks.DARKONITE_BLACK_CARVED);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
