
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.natureandharmony.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.world.level.levelgen.feature.Feature;

import net.mcreator.natureandharmony.world.features.plants.YellowBurstdflowerFeature;
import net.mcreator.natureandharmony.world.features.plants.WhiteRoseFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassTuftsFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassTallFrostedFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassTallFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassShortFrostedFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassPlantFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldGrassFrostedFeature;
import net.mcreator.natureandharmony.world.features.plants.UnderworldBellflowerFeature;
import net.mcreator.natureandharmony.world.features.plants.TallIceSpikeBlockFeature;
import net.mcreator.natureandharmony.world.features.plants.SunDialFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.RedRoseFeature;
import net.mcreator.natureandharmony.world.features.plants.PurpleBurstFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.PinkRoseFeature;
import net.mcreator.natureandharmony.world.features.plants.OpenFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.IceSpikeBlockFeature;
import net.mcreator.natureandharmony.world.features.plants.EminenceRootsFeature;
import net.mcreator.natureandharmony.world.features.plants.EminenceFungusFeature;
import net.mcreator.natureandharmony.world.features.plants.EminenceFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.DeadWeedsFeature;
import net.mcreator.natureandharmony.world.features.plants.DeadWeeds3Feature;
import net.mcreator.natureandharmony.world.features.plants.DeadWeeds2Feature;
import net.mcreator.natureandharmony.world.features.plants.CyanRoseFeature;
import net.mcreator.natureandharmony.world.features.plants.CirculatumFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.CactusFeature;
import net.mcreator.natureandharmony.world.features.plants.BuddedFlowerFeature;
import net.mcreator.natureandharmony.world.features.plants.AshTuffsFeature;
import net.mcreator.natureandharmony.world.features.ores.WitheredMossFeature;
import net.mcreator.natureandharmony.world.features.ores.VenomiteFeature;
import net.mcreator.natureandharmony.world.features.ores.VekreniteFeature;
import net.mcreator.natureandharmony.world.features.ores.UnderworldSandPurpleFeature;
import net.mcreator.natureandharmony.world.features.ores.UnderworldSandBrownFeature;
import net.mcreator.natureandharmony.world.features.ores.UnderworldGrassRedFloweredFeature;
import net.mcreator.natureandharmony.world.features.ores.UnderworldGrassFloweredfFeature;
import net.mcreator.natureandharmony.world.features.ores.SulphurOreFeature;
import net.mcreator.natureandharmony.world.features.ores.SilverOreFeature;
import net.mcreator.natureandharmony.world.features.ores.ScoriaRedFeature;
import net.mcreator.natureandharmony.world.features.ores.ScoriaGrayFeature;
import net.mcreator.natureandharmony.world.features.ores.RoseGoldOreFeature;
import net.mcreator.natureandharmony.world.features.ores.RhodusiteFeature;
import net.mcreator.natureandharmony.world.features.ores.QuartzDustBlockFeature;
import net.mcreator.natureandharmony.world.features.ores.PeakSchistFeature;
import net.mcreator.natureandharmony.world.features.ores.MossyNetherrackFeature;
import net.mcreator.natureandharmony.world.features.ores.MorgoniteFeature;
import net.mcreator.natureandharmony.world.features.ores.MicheriteOreFeature;
import net.mcreator.natureandharmony.world.features.ores.MarbleFeature;
import net.mcreator.natureandharmony.world.features.ores.LimestoneFeature;
import net.mcreator.natureandharmony.world.features.ores.GlowingObsidianFeature;
import net.mcreator.natureandharmony.world.features.ores.DarkoniteSnowyFeature;
import net.mcreator.natureandharmony.world.features.ores.CreamalenSmoothFeature;
import net.mcreator.natureandharmony.world.features.ores.CreamalenCobblestoneFeature;
import net.mcreator.natureandharmony.world.features.ores.CreamalanFeature;
import net.mcreator.natureandharmony.world.features.ores.CrackedCarboriteFeature;
import net.mcreator.natureandharmony.world.features.ores.CorkiteFeature;
import net.mcreator.natureandharmony.world.features.ores.ChalkWhiteFeature;
import net.mcreator.natureandharmony.world.features.ores.ChalkRedFeature;
import net.mcreator.natureandharmony.world.features.ores.ChalkBlueFeature;
import net.mcreator.natureandharmony.world.features.ores.BlackMarbleFeature;
import net.mcreator.natureandharmony.world.features.ores.BauxiteFeature;
import net.mcreator.natureandharmony.world.features.ores.AshGildedIronFeature;
import net.mcreator.natureandharmony.world.features.ores.AshGildedGoldFeature;
import net.mcreator.natureandharmony.world.features.ores.AshGildedDiamondFeature;
import net.mcreator.natureandharmony.world.features.ores.AshFeature;
import net.mcreator.natureandharmony.world.features.ores.AntimoniteFeature;
import net.mcreator.natureandharmony.world.features.ores.AnthraciteFeature;
import net.mcreator.natureandharmony.world.features.ores.ActiniumOreFeature;
import net.mcreator.natureandharmony.world.features.AshBarrensRocksFeature;
import net.mcreator.natureandharmony.NatureAndHarmonyMod;

@Mod.EventBusSubscriber
public class NatureAndHarmonyModFeatures {
	public static final DeferredRegister<Feature<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.FEATURES, NatureAndHarmonyMod.MODID);
	public static final RegistryObject<Feature<?>> ASH = REGISTRY.register("ash", AshFeature::new);
	public static final RegistryObject<Feature<?>> SULPHUR_ORE = REGISTRY.register("sulphur_ore", SulphurOreFeature::new);
	public static final RegistryObject<Feature<?>> MARBLE = REGISTRY.register("marble", MarbleFeature::new);
	public static final RegistryObject<Feature<?>> BLACK_MARBLE = REGISTRY.register("black_marble", BlackMarbleFeature::new);
	public static final RegistryObject<Feature<?>> LIMESTONE = REGISTRY.register("limestone", LimestoneFeature::new);
	public static final RegistryObject<Feature<?>> ANTIMONITE = REGISTRY.register("antimonite", AntimoniteFeature::new);
	public static final RegistryObject<Feature<?>> ANTHRACITE = REGISTRY.register("anthracite", AnthraciteFeature::new);
	public static final RegistryObject<Feature<?>> ASH_GILDED_GOLD = REGISTRY.register("ash_gilded_gold", AshGildedGoldFeature::new);
	public static final RegistryObject<Feature<?>> ASH_GILDED_IRON = REGISTRY.register("ash_gilded_iron", AshGildedIronFeature::new);
	public static final RegistryObject<Feature<?>> ASH_GILDED_DIAMOND = REGISTRY.register("ash_gilded_diamond", AshGildedDiamondFeature::new);
	public static final RegistryObject<Feature<?>> WITHERED_MOSS = REGISTRY.register("withered_moss", WitheredMossFeature::new);
	public static final RegistryObject<Feature<?>> RED_ROSE = REGISTRY.register("red_rose", RedRoseFeature::new);
	public static final RegistryObject<Feature<?>> PINK_ROSE = REGISTRY.register("pink_rose", PinkRoseFeature::new);
	public static final RegistryObject<Feature<?>> CYAN_ROSE = REGISTRY.register("cyan_rose", CyanRoseFeature::new);
	public static final RegistryObject<Feature<?>> WHITE_ROSE = REGISTRY.register("white_rose", WhiteRoseFeature::new);
	public static final RegistryObject<Feature<?>> ASH_TUFFS = REGISTRY.register("ash_tuffs", AshTuffsFeature::new);
	public static final RegistryObject<Feature<?>> EMINENCE_ROOTS = REGISTRY.register("eminence_roots", EminenceRootsFeature::new);
	public static final RegistryObject<Feature<?>> EMINENCE_FLOWER = REGISTRY.register("eminence_flower", EminenceFlowerFeature::new);
	public static final RegistryObject<Feature<?>> EMINENCE_FUNGUS = REGISTRY.register("eminence_fungus", EminenceFungusFeature::new);
	public static final RegistryObject<Feature<?>> MOSSY_NETHERRACK = REGISTRY.register("mossy_netherrack", MossyNetherrackFeature::new);
	public static final RegistryObject<Feature<?>> SCORIA_GRAY = REGISTRY.register("scoria_gray", ScoriaGrayFeature::new);
	public static final RegistryObject<Feature<?>> SCORIA_RED = REGISTRY.register("scoria_red", ScoriaRedFeature::new);
	public static final RegistryObject<Feature<?>> GLOWING_OBSIDIAN = REGISTRY.register("glowing_obsidian", GlowingObsidianFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_PLANT = REGISTRY.register("underworld_grass_plant", UnderworldGrassPlantFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_TUFTS = REGISTRY.register("underworld_grass_tufts", UnderworldGrassTuftsFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_FLOWEREDF = REGISTRY.register("underworld_grass_floweredf", UnderworldGrassFloweredfFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_TALL = REGISTRY.register("underworld_grass_tall", UnderworldGrassTallFeature::new);
	public static final RegistryObject<Feature<?>> PEAK_SCHIST = REGISTRY.register("peak_schist", PeakSchistFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_FROSTED = REGISTRY.register("underworld_grass_frosted", UnderworldGrassFrostedFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_SHORT_FROSTED = REGISTRY.register("underworld_grass_short_frosted", UnderworldGrassShortFrostedFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_TALL_FROSTED = REGISTRY.register("underworld_grass_tall_frosted", UnderworldGrassTallFrostedFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_BELLFLOWER = REGISTRY.register("underworld_bellflower", UnderworldBellflowerFeature::new);
	public static final RegistryObject<Feature<?>> PURPLE_BURST_FLOWER = REGISTRY.register("purple_burst_flower", PurpleBurstFlowerFeature::new);
	public static final RegistryObject<Feature<?>> YELLOW_BURSTDFLOWER = REGISTRY.register("yellow_burstdflower", YellowBurstdflowerFeature::new);
	public static final RegistryObject<Feature<?>> BUDDED_FLOWER = REGISTRY.register("budded_flower", BuddedFlowerFeature::new);
	public static final RegistryObject<Feature<?>> CIRCULATUM_FLOWER = REGISTRY.register("circulatum_flower", CirculatumFlowerFeature::new);
	public static final RegistryObject<Feature<?>> OPEN_FLOWER = REGISTRY.register("open_flower", OpenFlowerFeature::new);
	public static final RegistryObject<Feature<?>> SUN_DIAL_FLOWER = REGISTRY.register("sun_dial_flower", SunDialFlowerFeature::new);
	public static final RegistryObject<Feature<?>> CRACKED_CARBORITE = REGISTRY.register("cracked_carborite", CrackedCarboriteFeature::new);
	public static final RegistryObject<Feature<?>> VEKRENITE = REGISTRY.register("vekrenite", VekreniteFeature::new);
	public static final RegistryObject<Feature<?>> ROSE_GOLD_ORE = REGISTRY.register("rose_gold_ore", RoseGoldOreFeature::new);
	public static final RegistryObject<Feature<?>> BAUXITE = REGISTRY.register("bauxite", BauxiteFeature::new);
	public static final RegistryObject<Feature<?>> CORKITE = REGISTRY.register("corkite", CorkiteFeature::new);
	public static final RegistryObject<Feature<?>> MORGONITE = REGISTRY.register("morgonite", MorgoniteFeature::new);
	public static final RegistryObject<Feature<?>> VENOMITE = REGISTRY.register("venomite", VenomiteFeature::new);
	public static final RegistryObject<Feature<?>> RHODUSITE = REGISTRY.register("rhodusite", RhodusiteFeature::new);
	public static final RegistryObject<Feature<?>> MICHERITE_ORE = REGISTRY.register("micherite_ore", MicheriteOreFeature::new);
	public static final RegistryObject<Feature<?>> QUARTZ_DUST_BLOCK = REGISTRY.register("quartz_dust_block", QuartzDustBlockFeature::new);
	public static final RegistryObject<Feature<?>> ICE_SPIKE_BLOCK = REGISTRY.register("ice_spike_block", IceSpikeBlockFeature::new);
	public static final RegistryObject<Feature<?>> TALL_ICE_SPIKE_BLOCK = REGISTRY.register("tall_ice_spike_block", TallIceSpikeBlockFeature::new);
	public static final RegistryObject<Feature<?>> CHALK_WHITE = REGISTRY.register("chalk_white", ChalkWhiteFeature::new);
	public static final RegistryObject<Feature<?>> CHALK_BLUE = REGISTRY.register("chalk_blue", ChalkBlueFeature::new);
	public static final RegistryObject<Feature<?>> CHALK_RED = REGISTRY.register("chalk_red", ChalkRedFeature::new);
	public static final RegistryObject<Feature<?>> CREAMALAN = REGISTRY.register("creamalan", CreamalanFeature::new);
	public static final RegistryObject<Feature<?>> CREAMALEN_COBBLESTONE = REGISTRY.register("creamalen_cobblestone", CreamalenCobblestoneFeature::new);
	public static final RegistryObject<Feature<?>> CREAMALEN_SMOOTH = REGISTRY.register("creamalen_smooth", CreamalenSmoothFeature::new);
	public static final RegistryObject<Feature<?>> DARKONITE_SNOWY = REGISTRY.register("darkonite_snowy", DarkoniteSnowyFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_GRASS_RED_FLOWERED = REGISTRY.register("underworld_grass_red_flowered", UnderworldGrassRedFloweredFeature::new);
	public static final RegistryObject<Feature<?>> SILVER_ORE = REGISTRY.register("silver_ore", SilverOreFeature::new);
	public static final RegistryObject<Feature<?>> ACTINIUM_ORE = REGISTRY.register("actinium_ore", ActiniumOreFeature::new);
	public static final RegistryObject<Feature<?>> ASH_BARRENS_ROCKS = REGISTRY.register("ash_barrens_rocks", AshBarrensRocksFeature::new);
	public static final RegistryObject<Feature<?>> CACTUS = REGISTRY.register("cactus", CactusFeature::new);
	public static final RegistryObject<Feature<?>> DEAD_WEEDS = REGISTRY.register("dead_weeds", DeadWeedsFeature::new);
	public static final RegistryObject<Feature<?>> DEAD_WEEDS_2 = REGISTRY.register("dead_weeds_2", DeadWeeds2Feature::new);
	public static final RegistryObject<Feature<?>> DEAD_WEEDS_3 = REGISTRY.register("dead_weeds_3", DeadWeeds3Feature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_SAND_PURPLE = REGISTRY.register("underworld_sand_purple", UnderworldSandPurpleFeature::new);
	public static final RegistryObject<Feature<?>> UNDERWORLD_SAND_BROWN = REGISTRY.register("underworld_sand_brown", UnderworldSandBrownFeature::new);
}
